// remix/app/routes/login.tsx
import { Button, TextField, Typography, Alert, Collapse } from "@mui/material";
import { useEffect, useState } from "react";
import { Form, ActionFunction, MetaFunction, Link, useActionData, useSearchParams } from "remix";
import { ApiLoginRequest, ApiLoginResponse } from "~typings/api";
import { NAME_MIN_LENGTH, NAME_MAX_LENGTH, NAME_PATTERN, PASSWORD_MIN_LENGTH, PASSWORD_MAX_LENGTH, PASSWORD_PATTERN } from "~typings/constants";
import { LIBRARY_NAME } from "~typings/constants";
// @ts-ignore
import SwipeableViews from "react-swipeable-views";

export const meta: MetaFunction = () => {
  return {
    title: `登陆`,
    describe: `登陆到${LIBRARY_NAME}`,
  };
};

export const action: ActionFunction = async ({ request }) => {
  const body = await request.formData();
  const form = {
    email: "",
    name: body.get("name"),
    password: body.get("password"),
    capacity: "user",
  } as ApiLoginRequest;
  const result = (await (
    await fetch("http://localhost:1337/api/account/login", {
      method: "post",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify(form),
    })
  ).json()) as ApiLoginResponse;
  return result;
};

export default function Login() {
  const [loginForm, setLoginForm] = useState<ApiLoginRequest>({
    email: "",
    name: "",
    password: "",
    capacity: "user",
  });
  const [params, setParams] = useSearchParams();
  const [inputingPassword, setInputingPassword] = useState(false);
  const result = useActionData() as ApiLoginResponse | undefined;

  useEffect(() => {
    if (typeof result === "undefined") return;
    if (result.code !== "OK") {
      loginForm.password = "";
      setLoginForm(Object.assign({}, loginForm));
      return;
    }
    localStorage.setItem("access_token", `${result.accessToken}`);
    localStorage.setItem("refresh_token", `${result.refreshToken}`);
    window.location.href = "/";
  }, [result]);

  useEffect(() => {
    const isEditingPassword = !!params.get("editing") && params.get("editing") === "password";
    const nameValid = NAME_PATTERN.test(loginForm.name);
    if (isEditingPassword && nameValid) return setInputingPassword(true);
    if (isEditingPassword && !nameValid) return setParams({});
    setInputingPassword(false);
  }, [params]);

  return (
    <div className="absolute z-10 w-screen h-screen flex items-center justify-center">
      <div className="absolute w-screen h-screen bg-[#f0f0f0]"></div>

      <Form
        method="post"
        className={`flex flex-col z-10
            justify-between
            bg-[#f0f0f0]
            border-[#dadce0] border-[1px]
            px-16
            py-24
            w-full
            h-screen
            md:rounded md:shadow md:min-h-[500px]
            md:w-[448px] md:h-auto
            md:px-12 ${result && result.code !== "OK" ? "md:py-8" : "md:py-16"}
            transition-all
            duration-150
            ease-out`}
      >
        <div className="mb-4 flex-1 flex flex-col">
          <div className="mb-8">
            <Collapse in={result && result.code !== "OK"}>
              <Alert severity="error" variant="filled" className="mb-8">
                {result?.message}
              </Alert>
            </Collapse>
            <Typography variant="h5" className="mb-4 after:block after:mb-1">
              登陆
            </Typography>
            <Typography variant="body1">登陆到{LIBRARY_NAME}</Typography>
          </div>
          <div className="flex flex-col gap-y-8 mb-4">
            <SwipeableViews index={inputingPassword ? 1 : 0} style={{ overflowX: "clip" }} slideStyle={{ overflow: "unset" }}>
              <TextField
                autoFocus
                error={loginForm.name !== "" && !NAME_PATTERN.test(loginForm.name)}
                helperText={`${NAME_MIN_LENGTH}-${NAME_MAX_LENGTH}位，仅含字母数字和下划线`}
                fullWidth
                name="name"
                label="用户名"
                variant="outlined"
                type="text"
                value={loginForm.name}
                onChange={event => {
                  loginForm.name = event.target.value;
                  setLoginForm(Object.assign({}, loginForm));
                }}
              />
              <TextField
                error={loginForm.password !== "" && !PASSWORD_PATTERN.test(loginForm.password)}
                helperText={`${PASSWORD_MIN_LENGTH}-${PASSWORD_MAX_LENGTH}位，仅含字母数字和下划线`}
                fullWidth
                name="password"
                label="密码"
                variant="outlined"
                type="password"
                value={loginForm.password}
                onChange={event => {
                  loginForm.password = event.target.value;
                  setLoginForm(Object.assign({}, loginForm));
                }}
              />
            </SwipeableViews>
          </div>
          <div className="flex">
            <Link to={"/forget"}>
              <Typography color="primary" variant="button">
                忘记密码？
              </Typography>
            </Link>
          </div>
        </div>

        <div className="flex items-center justify-between">
          <Link to="/register" className="relative -left-2">
            <Button variant="text">创建账号</Button>
          </Link>
          {inputingPassword ? (
            <Button variant="contained" className="w-fit" type="submit" disabled={!PASSWORD_PATTERN.test(loginForm.password)}>
              提交
            </Button>
          ) : (
            <Button
              variant="contained"
              className="w-fit"
              type="button"
              disabled={!NAME_PATTERN.test(loginForm.name)}
              onClickCapture={event => {
                event.preventDefault();
                setParams({ editing: "password" });
              }}
            >
              下一步
            </Button>
          )}
        </div>
      </Form>
    </div>
  );
}

// web/src/pages/account/login.vue
<script lang="ts" setup>
import { ref, reactive } from "vue";
import {
  NForm,
  NFormItem,
  NInput,
  NH1,
  NP,
  NButton,
  NPopconfirm,
  FormRules,
  NAlert,
  AlertProps,
  NCollapseTransition,
} from "naive-ui";
import axios from "axios";
import type { ApiLoginRequest, ApiLoginResponse } from "@typings/api";
import { libraryName, librarySlogan } from "@/config";
import {
  PASSWORD_MAX_LENGTH,
  PASSWORD_MIN_LENGTH,
  PASSWORD_PATTERN,
  NAME_MAX_LENGTH,
  NAME_MIN_LENGTH,
  NAME_PATTERN,
} from "@typings/constants";

const loginFormRef = ref(null);
const alertType = ref<AlertProps["type"]>(undefined);
const alertTitle = ref("");
const alertMessage = ref("");
const loginFormData = reactive<ApiLoginRequest>({
  name: "",
  password: "",
  email: "",
  capacity: "user",
});
const loginFormRules: FormRules = {
  name: [
    { required: true, message: "请输入登录名" },
    {
      trigger: "blur",
      validator: (_rule, value) =>
        NAME_PATTERN.test(value) &&
        value.length >= NAME_MIN_LENGTH &&
        value.length <= NAME_MAX_LENGTH,
      message: `登录名仅能含数字、字母及下划线，长度位于${NAME_MIN_LENGTH}到${NAME_MAX_LENGTH}之间`,
    },
  ],
  password: [
    { required: true, message: "请输入密码" },
    {
      trigger: "blur",
      validator: (_rule, value) =>
        PASSWORD_PATTERN.test(value) &&
        value.length >= PASSWORD_MIN_LENGTH &&
        value.length <= PASSWORD_MAX_LENGTH,
      message: `密码仅能含数字、字母及下划线，密码长度位于${PASSWORD_MIN_LENGTH}到${PASSWORD_MAX_LENGTH}`,
    },
  ],
};

function handlePositiveClick() {
  loginFormData.name = "";
  loginFormData.password = "";
}
function handleLogin() {
  // @ts-ignore
  loginFormRef.value.validate(errors => {
    if (errors) return console.log(errors);
    axios
      .post<ApiLoginResponse>("/api/account/login", {
        name: loginFormData.name,
        password: loginFormData.password,
      })
      .then(result => {
        if (result.data.code === "OK") {
          if (result.data.accessToken && result.data.refreshToken) {
            localStorage.setItem("access_token", result.data.accessToken);
            localStorage.setItem("refresh_token", result.data.refreshToken);
            window.location.href = "/";
          } else {
            alertType.value = "error";
            alertTitle.value = "服务器出错";
            alertMessage.value = "服务接口有误，未返回令牌，请稍后再试。";
            setTimeout(() => {
              alertType.value = undefined;
              alertTitle.value = "";
              alertMessage.value = "";
            }, 8000);
          }
        } else {
          alertType.value = "error";
          alertTitle.value = "登陆失败";
          alertMessage.value = result.data.message;
          setTimeout(() => {
            alertType.value = undefined;
            alertTitle.value = "";
            alertMessage.value = "";
          }, 8000);
        }
      })
      .catch(error => {
        alertType.value = "error";
        alertTitle.value = "登陆失败";
        alertMessage.value = error.message;
      });
  });
}
</script>

<template>
  <div class="absolute z-10 w-screen h-screen flex items-center justify-center">
    <n-form
      ref="loginFormRef"
      :model="loginFormData"
      :rules="loginFormRules"
      :show-require-mark="false"
      class="flex flex-col justify-between bg-[#f0f0f0] px-10 py-14 w-full h-screen md:rounded md:shadow md:w-96 md:px-8 md:py-4 md:h-auto transition-all duration-150 ease-out"
      label-align="left"
      label-placement="left"
      label-width="80px"
    >
      <div>
        <n-collapse-transition :show="!!alertType">
          <n-alert :title="alertTitle" :type="alertType" class="alert-message mb-5">
            {{ alertMessage }}
          </n-alert>
        </n-collapse-transition>
        <n-h1 :strong="true" class="cursor-pointer" v-text="libraryName" />
        <n-p class="cursor-pointer mb-8" v-text="librarySlogan" />
        <n-form-item class="mb-2 cursor-pointer" first label="登陆名" path="name">
          <n-input v-model:value="loginFormData.name" />
        </n-form-item>

        <n-form-item class="mb-2 cursor-pointer" first label="密码" path="password">
          <n-input
            v-model:value="loginFormData.password"
            :maxlength="16"
            :minlength="8"
            show-password-on="click"
            type="password"
          />
        </n-form-item>
      </div>

      <div>
        <div class="mt-6 flex justify-end">
          <n-popconfirm @positive-click="handlePositiveClick">
            <template #trigger>
              <n-button class="mr-2" round>清除</n-button>
            </template>
            确定重置数据
          </n-popconfirm>
          <n-button round type="info" @click="handleLogin">登陆</n-button>
        </div>
      </div>
    </n-form>
  </div>
  <div class="w-screen h-screen bg-slate-600"></div>
</template>
